### ISSUE TITLE
Have a $(date)

### ISSUE THREAD

**Issue by nonniv** [Gigabyte-Giant/vscode-file-header-comment-helper#13]
Hi, I would like to have option for $(date) in the comment template, that would be replaced with the date the comment is inserted.

**Comment by nonniv** [comment]
i see this is option in the code but it dosn´t seems to work for me.

**Comment by Gigabyte-Giant** [comment]
This functionality has indeed been implemented, however, the extension available on the Visual Studio Code marketplace has not yet been updated.

Closing this in favor of https://github.com/Gigabyte-Giant/vscode-file-header-comment-helper/issues/10.
